export const FETCH_CANDIDATES_REQUEST = 'candidates/FETCH_CANDIDATES_REQUEST';
export const FETCH_CANDIDATES_SUCCESS = 'candidates/FETCH_CANDIDATES_SUCCESS';
export const FETCH_CANDIDATES_FAILURE = 'candidates/FETCH_CANDIDATES_FAILURE';

export const FETCH_CANDIDATE_BY_ID_REQUEST = 'candidates/FETCH_CANDIDATE_BY_ID_REQUEST';
export const FETCH_CANDIDATE_BY_ID_SUCCESS = 'candidates/FETCH_CANDIDATE_BY_ID_SUCCESS';
export const FETCH_CANDIDATE_BY_ID_FAILURE = 'candidates/FETCH_CANDIDATE_BY_ID_FAILURE';

export const CREATE_CANDIDATE_REQUEST = 'candidates/CREATE_CANDIDATE_REQUEST';
export const CREATE_CANDIDATE_SUCCESS = 'candidates/CREATE_CANDIDATE_SUCCESS';
export const CREATE_CANDIDATE_FAILURE = 'candidates/CREATE_CANDIDATE_FAILURE';

export const COMPARE_CANDIDATES_REQUEST = 'candidates/COMPARE_CANDIDATES_REQUEST';
export const COMPARE_CANDIDATES_SUCCESS = 'candidates/COMPARE_CANDIDATES_SUCCESS';
export const COMPARE_CANDIDATES_FAILURE = 'candidates/COMPARE_CANDIDATES_FAILURE';

export const DELETE_CANDIDATE_REQUEST = 'candidates/DELETE_CANDIDATE_REQUEST';
export const DELETE_CANDIDATE_SUCCESS = 'candidates/DELETE_CANDIDATE_SUCCESS';
export const DELETE_CANDIDATE_FAILURE = 'candidates/DELETE_CANDIDATE_FAILURE';
